### ISSUE TITLE
Release 0.2.0-rc.0 only works with RN0.60 (androidx) [FIX INCLUDED]

### ISSUE THREAD

**Issue by nschild** [expo/react-native-appearance#16]
We are not using androidX yet and we're getting this error while compiling:

    > Task :react-native-appearance:compileDebugJavaWithJavac FAILED
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCAppearanceManager.java:3: error: cannot find symbol
    import android.annotation.NonNull;
                            ^
    symbol:   class NonNull
    location: package android.annotation
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperancePackage.java:3: error: cannot find symbol
    import android.annotation.NonNull;
                            ^
    symbol:   class NonNull
    location: package android.annotation
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperanceModule.java:11: error: cannot find symbol
    import android.annotation.NonNull;
                            ^
    symbol:   class NonNull
    location: package android.annotation
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperanceModule.java:12: error: cannot find symbol
    import android.annotation.Nullable;
                            ^
    symbol:   class Nullable
    location: package android.annotation
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCAppearanceManager.java:10: error: cannot find symbol
        @NonNull
        ^
    symbol:   class NonNull
    location: class RNCAppearanceManager
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCAppearanceManager.java:18: error: cannot find symbol
        protected RNCAppearanceProvider createViewInstance(@NonNull ThemedReactContext reactContext) {
                                                            ^
    symbol:   class NonNull
    location: class RNCAppearanceManager
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCAppearanceManager.java:16: error: cannot find symbol
        @NonNull
        ^
    symbol:   class NonNull
    location: class RNCAppearanceManager
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperancePackage.java:17: error: cannot find symbol
        public List<NativeModule> createNativeModules(@NonNull ReactApplicationContext reactContext) {
                                                    ^
    symbol:   class NonNull
    location: class RNCApperancePackage
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperancePackage.java:15: error: cannot find symbol
        @NonNull
        ^
    symbol:   class NonNull
    location: class RNCApperancePackage
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperancePackage.java:25: error: cannot find symbol
        public List<ViewManager> createViewManagers(@NonNull ReactApplicationContext reactContext) {
                                                    ^
    symbol:   class NonNull
    location: class RNCApperancePackage
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperancePackage.java:23: error: cannot find symbol
        @NonNull
        ^
    symbol:   class NonNull
    location: class RNCApperancePackage
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperanceModule.java:31: error: cannot find symbol
        public RNCApperanceModule(@NonNull ReactApplicationContext reactContext) {
                                ^
    symbol:   class NonNull
    location: class RNCApperanceModule
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperanceModule.java:47: error: cannot find symbol
        @NonNull
        ^
    symbol:   class NonNull
    location: class RNCApperanceModule
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperanceModule.java:82: error: cannot find symbol
        @androidx.annotation.Nullable
                            ^
    symbol:   class Nullable
    location: package androidx.annotation
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperanceModule.java:90: error: cannot find symbol
        private void sendEvent(ReactContext reactContext, String eventName, @Nullable WritableMap params) {
                                                                            ^
    symbol:   class Nullable
    location: class RNCApperanceModule
    /path/to/app/node_modules/react-native-appearance/android/src/main/java/com/reactlibrary/RNCApperanceModule.java:100: error: cannot find symbol
        private void sendEvent(String eventName, @Nullable WritableMap params) {
                                                ^
    symbol:   class Nullable
    location: class RNCApperanceModule
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    16 errors

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':react-native-appearance:compileDebugJavaWithJavac'.
    > Compilation failed; see the compiler error output for details.

For those whom want an easy fix, use the patch file:
https://gist.github.com/nschild/0c9ded2e04af98054aca27d6359a2947

Also, add the following line to your build.gradle's dependencies section:
`implementation 'com.android.support:support-annotations:+'`

**Comment by brentvatne** [comment]
thanks! can you open a pull request for this?

**Comment by rolandjitsu** [comment]
Is there a previous release we can use meanwhile?

**Comment by nschild** [comment]
@brentvatne I am not sure of what path the team wants to take on this. If they accept my PR, AndroidX will not work, and since AndroidX is the future, I doubt it should be included.

@rolandjitsu all you have to do is run `npm install patch-package`, add `"scripts": { "postinstall":  "patch-package";}` to your package.json and place the above file into a /patches/ folder in your root directory. Now, when node installs react-native-appearance, it will automatically apply the patch file.

**Comment by thiagoferolla** [comment]
This problem can be solved for react-native 0.59 by using jetifier, running `npx jetify -r`

**Comment by mikehardy** [comment]
Jetifier is the community answer for handling library/project android/androidx mismatch

**Comment by brentvatne** [comment]
added instructions under readme: https://github.com/expo/react-native-appearance#linking
